---
# Source: busybox-web/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: busybox
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: busybox-web
    app.kubernetes.io/instance: release-name
  ports:
    - name: http
      port: 8081
      targetPort: 8080
---
# Source: busybox-web/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: busybox-web
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: busybox-web
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: busybox-web
          image: "busybox:1.36"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          command:
            - sh
            - -c
            - |
              set -eu
              mkdir -p /www;
              cat << 'EOF' > /www/index.html
              BusyBox up and running 🚀
              
              EOF
              httpd -f -p 8080 -h /www
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {}
